// <auto-generated />
using System;
using BeerSender.Web.Read_database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeerSender.Web.Migrations.Read_contextMigrations
{
    [DbContext(typeof(Read_context))]
    partial class Read_contextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BeerSender.Web.Read_database.Bottles_model", b =>
                {
                    b.Property<Guid>("Bottle_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Alcohol_percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Bottles_sold")
                        .HasColumnType("int");

                    b.Property<string>("Brewery")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar");

                    b.Property<int>("Volume_in_ml")
                        .HasColumnType("int");

                    b.HasKey("Bottle_id");

                    b.ToTable("Bottles");
                });

            modelBuilder.Entity("BeerSender.Web.Read_database.Box_status", b =>
                {
                    b.Property<Guid>("Aggregate_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Number_of_bottles")
                        .HasColumnType("int");

                    b.Property<int>("Shipment_status")
                        .HasColumnType("int");

                    b.HasKey("Aggregate_id");

                    b.ToTable("Box_statuses");
                });

            modelBuilder.Entity("BeerSender.Web.Read_database.Projection_checkpoint", b =>
                {
                    b.Property<string>("Projection_name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<byte[]>("Event_version")
                        .IsRequired()
                        .HasColumnType("binary(8)");

                    b.HasKey("Projection_name");

                    b.ToTable("Projection_checkpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
